import {
  HiOutlineSquares2X2,
  HiOutlineUserGroup,
  HiOutlineCalendarDays,
  HiOutlineChatBubbleLeftRight,
  HiOutlineBell,
  HiOutlineNewspaper,
  HiOutlineChartBar,
  HiOutlineDocumentText,
  HiOutlineCog6Tooth,
  HiOutlineWrenchScrewdriver,
  HiOutlineUsers,
  HiOutlineRectangleGroup,
  HiOutlineHome,
  HiOutlineShieldExclamation,
  HiOutlineShieldCheck,
  HiOutlineClipboardDocumentList,
  HiOutlineBriefcase,
  HiOutlineUser,
  HiOutlineMapPin,
  HiOutlineDocumentCheck,
} from 'react-icons/hi2';
import { ROLES } from './roles';

// Sidebar menus keyed by role. `to` paths must exist in AppRoutes and the role
// must hold the matching permission (routes re-check via RoleRoute/PermissionRoute).
// `labelKey` is an i18next key (translated at render time in Sidebar.jsx).
export const SIDEBAR_NAV = {
  [ROLES.CITIZEN]: [
    { to: '/dashboard/citizen', labelKey: 'nav.dashboard', icon: HiOutlineSquares2X2 },
    { to: '/workers', labelKey: 'nav.workers', icon: HiOutlineUserGroup },
    { to: '/categories', labelKey: 'nav.categories', icon: HiOutlineRectangleGroup },
    { to: '/bookings', labelKey: 'nav.bookings', icon: HiOutlineCalendarDays },
    { to: '/chat', labelKey: 'nav.chat', icon: HiOutlineChatBubbleLeftRight },
    { to: '/news', labelKey: 'nav.news', icon: HiOutlineNewspaper },
    { to: '/family', labelKey: 'nav.family', icon: HiOutlineHome },
    { to: '/emergency', labelKey: 'nav.emergency', icon: HiOutlineShieldExclamation },
    { to: '/notifications', labelKey: 'nav.notifications', icon: HiOutlineBell },
    { to: '/settings', labelKey: 'nav.settings', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.WORKER]: [
    { to: '/dashboard/worker', labelKey: 'nav.dashboard', icon: HiOutlineSquares2X2 },
    { to: '/provider/services', labelKey: 'nav.providerServices', icon: HiOutlineWrenchScrewdriver },
    { to: '/bookings', labelKey: 'nav.bookings', icon: HiOutlineCalendarDays },
    { to: '/chat', labelKey: 'nav.chat', icon: HiOutlineChatBubbleLeftRight },
    { to: '/provider/documents', labelKey: 'nav.providerDocuments', icon: HiOutlineDocumentCheck },
    { to: '/notifications', labelKey: 'nav.notifications', icon: HiOutlineBell },
    { to: '/settings', labelKey: 'nav.settings', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.ORGANIZATION]: [
    { to: '/dashboard/organization', labelKey: 'nav.dashboard', icon: HiOutlineSquares2X2 },
    { to: '/workers', labelKey: 'nav.workers', icon: HiOutlineUserGroup },
    { to: '/bookings', labelKey: 'nav.jobPostings', icon: HiOutlineBriefcase },
    { to: '/chat', labelKey: 'nav.chat', icon: HiOutlineChatBubbleLeftRight },
    { to: '/profile', labelKey: 'nav.orgProfile', icon: HiOutlineUser },
    { to: '/notifications', labelKey: 'nav.notifications', icon: HiOutlineBell },
    { to: '/settings', labelKey: 'nav.settings', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.MAHALLA_ADMIN]: [
    { to: '/dashboard/mahalla', labelKey: 'nav.dashboard', icon: HiOutlineSquares2X2 },
    { to: '/admin/workers', labelKey: 'nav.workersVerify', icon: HiOutlineWrenchScrewdriver },
    { to: '/admin/users', labelKey: 'nav.residents', icon: HiOutlineUsers },
    { to: '/news', labelKey: 'nav.announcements', icon: HiOutlineNewspaper },
    { to: '/analytics', labelKey: 'nav.reports', icon: HiOutlineChartBar },
    { to: '/settings', labelKey: 'nav.settings', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.DISTRICT_ADMIN]: [
    { to: '/dashboard/district', labelKey: 'nav.dashboard', icon: HiOutlineSquares2X2 },
    { to: '/admin/management', labelKey: 'nav.admins', icon: HiOutlineShieldCheck },
    { to: '/admin/users', labelKey: 'nav.users', icon: HiOutlineUsers },
    { to: '/admin/workers', labelKey: 'nav.workers', icon: HiOutlineWrenchScrewdriver },
    { to: '/analytics', labelKey: 'nav.analytics', icon: HiOutlineChartBar },
    { to: '/reports', labelKey: 'nav.reports', icon: HiOutlineDocumentText },
    { to: '/settings', labelKey: 'nav.settings', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.REGION_ADMIN]: [
    { to: '/dashboard/region', labelKey: 'nav.dashboard', icon: HiOutlineSquares2X2 },
    { to: '/admin/management', labelKey: 'nav.admins', icon: HiOutlineShieldCheck },
    { to: '/admin/users', labelKey: 'nav.users', icon: HiOutlineUsers },
    { to: '/analytics', labelKey: 'nav.analytics', icon: HiOutlineChartBar },
    { to: '/reports', labelKey: 'nav.reports', icon: HiOutlineDocumentText },
    { to: '/settings', labelKey: 'nav.settings', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.SUPER_ADMIN]: [
    { to: '/dashboard/admin', labelKey: 'nav.dashboard', icon: HiOutlineSquares2X2 },
    { to: '/admin/management', labelKey: 'nav.admins', icon: HiOutlineShieldCheck },
    { to: '/admin/users', labelKey: 'nav.users', icon: HiOutlineUsers },
    { to: '/admin/workers', labelKey: 'nav.workers', icon: HiOutlineWrenchScrewdriver },
    { to: '/admin/categories', labelKey: 'nav.categoriesAdmin', icon: HiOutlineRectangleGroup },
    { to: '/admin/locations', labelKey: 'nav.locationsAdmin', icon: HiOutlineMapPin },
    { to: '/admin/audit-logs', labelKey: 'nav.auditLogs', icon: HiOutlineClipboardDocumentList },
    { to: '/analytics', labelKey: 'nav.analyticsShort', icon: HiOutlineChartBar },
    { to: '/reports', labelKey: 'nav.reports', icon: HiOutlineDocumentText },
    { to: '/settings', labelKey: 'nav.settings', icon: HiOutlineCog6Tooth },
  ],
};
