import {
  HiOutlineSquares2X2,
  HiOutlineUserGroup,
  HiOutlineCalendarDays,
  HiOutlineChatBubbleLeftRight,
  HiOutlineBell,
  HiOutlineNewspaper,
  HiOutlineCreditCard,
  HiOutlineExclamationTriangle,
  HiOutlineStar,
  HiOutlineChartBar,
  HiOutlineDocumentText,
  HiOutlineCog6Tooth,
  HiOutlineWrenchScrewdriver,
  HiOutlineUsers,
  HiOutlineRectangleGroup,
  HiOutlineCalendar,
  HiOutlineHome,
  HiOutlineShieldExclamation,
  HiOutlineShieldCheck,
  HiOutlineClipboardDocumentList,
  HiOutlineBriefcase,
  HiOutlineUser,
  HiOutlineMapPin,
  HiOutlineDocumentCheck,
} from 'react-icons/hi2';
import { ROLES } from './roles';

// Sidebar menus keyed by role. `to` paths must exist in AppRoutes and the role
// must hold the matching permission (routes re-check via RoleRoute/PermissionRoute).
export const SIDEBAR_NAV = {
  [ROLES.CITIZEN]: [
    { to: '/dashboard/citizen', label: 'Boshqaruv', icon: HiOutlineSquares2X2 },
    { to: '/workers', label: 'Ustalar', icon: HiOutlineUserGroup },
    { to: '/categories', label: 'Kategoriyalar', icon: HiOutlineRectangleGroup },
    { to: '/bookings', label: 'Buyurtmalar', icon: HiOutlineCalendarDays },
    { to: '/chat', label: 'Suhbatlar', icon: HiOutlineChatBubbleLeftRight },
    { to: '/complaints', label: 'Murojaatlar', icon: HiOutlineExclamationTriangle },
    { to: '/news', label: 'Yangiliklar', icon: HiOutlineNewspaper },
    { to: '/events', label: 'Tadbirlar', icon: HiOutlineCalendar },
    { to: '/family', label: 'Oilam', icon: HiOutlineHome },
    { to: '/emergency', label: 'Favqulodda', icon: HiOutlineShieldExclamation },
    { to: '/notifications', label: 'Bildirishnomalar', icon: HiOutlineBell },
    { to: '/settings', label: 'Sozlamalar', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.WORKER]: [
    { to: '/dashboard/worker', label: 'Boshqaruv', icon: HiOutlineSquares2X2 },
    { to: '/provider/services', label: 'Xizmatlarim', icon: HiOutlineWrenchScrewdriver },
    { to: '/bookings', label: 'Buyurtmalar', icon: HiOutlineCalendarDays },
    { to: '/chat', label: 'Suhbatlar', icon: HiOutlineChatBubbleLeftRight },
    { to: '/reviews', label: 'Sharhlar', icon: HiOutlineStar },
    { to: '/provider/documents', label: 'Hujjatlar', icon: HiOutlineDocumentCheck },
    { to: '/notifications', label: 'Bildirishnomalar', icon: HiOutlineBell },
    { to: '/settings', label: 'Sozlamalar', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.ORGANIZATION]: [
    { to: '/dashboard/organization', label: 'Boshqaruv', icon: HiOutlineSquares2X2 },
    { to: '/workers', label: 'Ustalar', icon: HiOutlineUserGroup },
    { to: '/bookings', label: 'Ish e\'lonlari', icon: HiOutlineBriefcase },
    { to: '/chat', label: 'Suhbatlar', icon: HiOutlineChatBubbleLeftRight },
    { to: '/profile', label: 'Tashkilot profili', icon: HiOutlineUser },
    { to: '/notifications', label: 'Bildirishnomalar', icon: HiOutlineBell },
    { to: '/settings', label: 'Sozlamalar', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.MAHALLA_ADMIN]: [
    { to: '/dashboard/mahalla', label: 'Boshqaruv', icon: HiOutlineSquares2X2 },
    { to: '/admin/workers', label: 'Ustalar (tasdiq)', icon: HiOutlineWrenchScrewdriver },
    { to: '/admin/users', label: 'Aholi', icon: HiOutlineUsers },
    { to: '/complaints', label: 'Murojaatlar', icon: HiOutlineExclamationTriangle },
    { to: '/news', label: 'E\'lonlar', icon: HiOutlineNewspaper },
    { to: '/analytics', label: 'Hisobotlar', icon: HiOutlineChartBar },
    { to: '/settings', label: 'Sozlamalar', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.DISTRICT_ADMIN]: [
    { to: '/dashboard/district', label: 'Boshqaruv', icon: HiOutlineSquares2X2 },
    { to: '/admin/management', label: 'Administratorlar', icon: HiOutlineShieldCheck },
    { to: '/admin/users', label: 'Foydalanuvchilar', icon: HiOutlineUsers },
    { to: '/admin/workers', label: 'Ustalar', icon: HiOutlineWrenchScrewdriver },
    { to: '/analytics', label: 'Statistika', icon: HiOutlineChartBar },
    { to: '/reports', label: 'Hisobotlar', icon: HiOutlineDocumentText },
    { to: '/settings', label: 'Sozlamalar', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.REGION_ADMIN]: [
    { to: '/dashboard/region', label: 'Boshqaruv', icon: HiOutlineSquares2X2 },
    { to: '/admin/management', label: 'Administratorlar', icon: HiOutlineShieldCheck },
    { to: '/admin/users', label: 'Foydalanuvchilar', icon: HiOutlineUsers },
    { to: '/analytics', label: 'Statistika', icon: HiOutlineChartBar },
    { to: '/reports', label: 'Hisobotlar', icon: HiOutlineDocumentText },
    { to: '/settings', label: 'Sozlamalar', icon: HiOutlineCog6Tooth },
  ],
  [ROLES.SUPER_ADMIN]: [
    { to: '/dashboard/admin', label: 'Boshqaruv', icon: HiOutlineSquares2X2 },
    { to: '/admin/management', label: 'Administratorlar', icon: HiOutlineShieldCheck },
    { to: '/admin/users', label: 'Foydalanuvchilar', icon: HiOutlineUsers },
    { to: '/admin/workers', label: 'Ustalar', icon: HiOutlineWrenchScrewdriver },
    { to: '/admin/categories', label: 'Kategoriyalar', icon: HiOutlineRectangleGroup },
    { to: '/admin/locations', label: 'Hududlar', icon: HiOutlineMapPin },
    { to: '/admin/audit-logs', label: 'Audit jurnali', icon: HiOutlineClipboardDocumentList },
    { to: '/payments', label: "To'lovlar", icon: HiOutlineCreditCard },
    { to: '/analytics', label: 'Analitika', icon: HiOutlineChartBar },
    { to: '/reports', label: 'Hisobotlar', icon: HiOutlineDocumentText },
    { to: '/settings', label: 'Sozlamalar', icon: HiOutlineCog6Tooth },
  ],
};
